repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        name: Unspecific | Prevent Commits to Protected Branches
        args: ["--branch", "main", "--branch", "master"]
      - id: trailing-whitespace
        name: Arbitrary | Trim Trailing Whitespaces
      - id: end-of-file-fixer
        name: Arbitrary | Fix End of Files
      - id: check-case-conflict
        name: Arbitrary | Case Conflict Check
      - id: check-illegal-windows-names
        name: Arbitrary | Illegal Windows Names Check
      - id: detect-private-key
        name: Arbitrary | Detect Private Keys
      - id: mixed-line-ending
        name: Arbitrary | Check and Fix Mixed Line Endings
        args: ["--fix=no"]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
        name: Arbitrary | Detect Hardcoded Secrets
        args: ["detect", "-v"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Markdown | Format with Prettier
        types: [markdown]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.0.14
    hooks:
      - id: markdownlint-cli2
        name: Markdown | Lint with Markdownlint
        types: [markdown]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: Shell Scripting | Lint with ShellCheck
        args: ["--severity", "style"]
        types: [shell]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Python | Format with Black
  # - repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.4.0
  #   hooks:
  #     - id: nbqa-black
  #       name: Jupyter Notebooks | Format with Black
  #       additional_dependencies:
  #         - "black==23.3.0"
  #       args: ["--line-length=80"]
  #       types: [jupyter]
  #     - id: nbqa-isort
  #       name: Jupyter Notebooks | Sort Imports in Notebooks
  #       additional_dependencies:
  #         - "isort==5.12.0"
  #       types: [jupyter]
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: Jupyter Notebooks | Clear Output Cells
        types: [jupyter]
        stages: [pre-commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
        name: JSON | Check Syntax
        types: [json]
      - id: check-xml
        name: XML | Check Syntax
        types: [xml]
      - id: check-yaml
        name: YAML | Check Syntax
        types: [yaml]
  - repo: https://github.com/google/yamlfmt
    rev: v0.12.0
    hooks:
      - id: yamlfmt
        name: YAML | Format with YAMLfmt
        types: [yaml]
